# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: ["dui3/alpha"]

jobs:
  build:

    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-version.outputs.version }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Set connector version
      run: |
        python patch_version.py 3.0.0-fake
    - name: â¬†ï¸ Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: output-3.0.0-fake
        path: |
          speckle_connector_3.rb
          speckle_connector_3/**/*
        compression-level: 0 # no compression
    - id: set-version
      name: Set version to output
      run: echo "version=3.0.0-fake" >> "$GITHUB_OUTPUT" # version will be retrieved from tag?
        

  deploy-installers:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: ðŸ”« Trigger Build Installers
        uses: ALEEF02/workflow-dispatch@v3.0.0
        with:
          workflow: Build Sketchup
          repo: specklesystems/connector-installers
          token: ${{ secrets.CONNECTORS_GH_TOKEN }}
          inputs: '{ "run_id": "${{ github.run_id }}", "version": "${{ needs.build.outputs.version }}" }'
          ref: main
          wait-for-completion: true
          wait-for-completion-interval: 10s
          wait-for-completion-timeout: 10m
          display-workflow-run-url: true
          display-workflow-run-url-interval: 10s
      
